version: '2'
services:
  db:
    build: ./docker/database/
    volumes:
      - postgres:/var/lib/postgresql/data:rw
  bot:
    build: .
    command: python manage.py bot -e docker
    volumes:
      - .:/opt/referee
    ports:
      - "7272:7171"
    depends_on:
      - db
volumes:
  postgres: {}
